apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kube-iyadbitar-com-tls
spec:
  secretName: kube-iyadbitar-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kube.iyadbitar.com
  dnsNames:
    - kube.iyadbitar.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kube.iyadbitar.com